spring:
  application:
    name: gradquest-backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gradquest?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: gradquest
    password: Gradquest123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  servlet:
    context-path: /api/v1
  port: 5000 # 设置应用运行的端口号为5000

# PDF Agent 配置
doubao:
  api:
    key: "eba95612-5bd7-4cee-96df-3a384d61a230" # 硬编码的 API Key
  model: doubao-seed-1-6-251015
  base:
    url: https://ark.cn-beijing.volces.com/api/v3

logging:
  level:
    com.zaxxer.hikari: DEBUG