spring:
  application:
    name: gradquest-backend
  datasource:
    url: jdbc:mysql://113.44.142.91:3306/gradquest
    username: zzr
    password: Zzr123456!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  servlet:
    context-path: /api/v1
  port: 5000 # 设置应用运行的端口号为5000

# PDF Agent 配置
doubao:
  api:
    key: ${ARK_API_KEY:} # 从环境变量读取，如果没有则使用空字符串
  model: doubao-seed-1-6-251015
  base:
    url: https://ark.cn-beijing.volces.com/api/v3
